---
title: "506 Data Merge"
output:
  html_document: default
  pdf_document: default
date: "2022-11-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r}
library(dplyr)
```

```{r}
ca <- read.csv("/Users/VickiChang/Desktop/506 Data Files/ca.csv")
ca_epa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/ca_epa.csv")
ca <- ca[,-1]
```

```{r}
ca$county <- stringr::str_trim(ca$county)
ca_full <- left_join(ca, ca_epa, by = "county")
ca_full <- ca_full[,c(1:7,9,10)]
colnames(ca_full)[which(colnames(ca_full) == "year.x")] <- "year"
```

```{r}
or <- read.csv("/Users/VickiChang/Desktop/506 Data Files/or.csv")
or_epa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/or_epa.csv")
```

```{r}
or$county <- stringr::str_trim(or$county)
or_full <- left_join(or[,-1], or_epa, by = "county")
or_full <- or_full[,c(1:7,9,10)]
colnames(or_full)[which(colnames(or_full) == "year.x")] <- "year"
```

```{r}
wa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/wa.csv")
wa_epa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/wa_epa.csv")
```

```{r}
wa$county <- stringr::str_trim(wa$county)
wa_full <- left_join(wa[,-1], wa_epa, by = "county")
wa_full <- wa_full[,c(1:7,9,10)]
colnames(wa_full)[which(colnames(wa_full) == "year.x")] <- "year"
```

```{r}
write.csv(ca_full, "/Users/VickiChang/Desktop/ca_full.csv")
write.csv(or_full, "/Users/VickiChang/Desktop/or_full.csv")
write.csv(wa_full, "/Users/VickiChang/Desktop/wa_full.csv")
```

```{r message = FALSE, echo = TRUE, results = "hide"}
### Comment out these lines of code; this will change depending on who's running the code, and I think we all have the census key stored in our environment 
# census_api_key("2567b1d4e4122ec716ee4e55fce64f07a9cbae74", install = TRUE, overwrite = TRUE)
# Sys.setenv(CENSUS_API_KEY='Your API key here as a string' )
# Reload .Renviron
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_API_KEY")
```

```{r}
ca1 <- population_func(2012, "CA")
```

