---
title: "506 Project Functions"
output:
  html_document: default
  pdf_document: default
date: "2022-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r warning = FALSE, message = FALSE}
library(writexl)
library(dplyr)
suppressWarnings(library(kableExtra))
library(tidycensus)
library(tigris)
library(tidyverse)
```

```{r message = FALSE, echo = TRUE, results = "hide"}
### Comment out these lines of code; this will change depending on who's running the code, and I think we all have the census key stored in our environment 
# census_api_key("2567b1d4e4122ec716ee4e55fce64f07a9cbae74", install = TRUE, overwrite = TRUE)
# Sys.setenv(CENSUS_API_KEY='Your API key here as a string' )
# Reload .Renviron
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_API_KEY")
```

# Function 1

Create a function to extract data from the Census API
- Inputs: state, year
- Output: a dataframe with the population for each demographic group for each year for each county in the state

```{r}
census_var <- load_variables(year = 2010, dataset = 'sf1', cache=T)
# All races except for hispanic or latino
census_race <- census_var[grepl("^RACE$", census_var$concept), ]
### as well as "Total!!", which are the different demographic groups
census_race1 <- census_race[grepl("^Total!!", census_race$label), ]
### Include the "Total" population
census_race1 <- rbind(census_race1, census_race%>%filter(label == "Total" & name == "P003001")) ### There were 3 "Total" variables; upon investigating each, only keep P003001, which is the total population
### Create a variable with the race
census_race1$race <- substring(census_race1$label, 8)
```

```{r}
### At this point, there are many races
unique(census_race1$race)
```



```{r}
### If the race is an empty string "", that's the total population
census_race1$race <- ifelse(census_race1$race == "", "Total", census_race1$race)
### Filter to a subset of races
races <- census_race1%>%
  filter(
  race %in% c("White alone", 
              "Black alone", 
              "American Indian and Alaska Native alone", 
              "Asian alone", 
              "Native Hawaiian and Other Pacific Islander alone", 
              "Some Other Race alone",
              ### Also include people who are two or more races 
              "Two or More Races",
              "Total"))

#### Find the total hispanic or latino origin
race_hl <- census_var[grepl("^HISPANIC OR LATINO ORIGIN BY RACE", census_var$concept), ]
total_hl <- race_hl[grepl("^Total$", race_hl$label), ]
### Change the label to be "TotalHispanicLatino", to separate from the total population
total_hl$label <- "TotalHispanicLatino"
total_hl$race <- c("Hispanic or Latino")
all_races <- rbind(races, total_hl) ### 
race_codes <- all_races[,1]
### These are the variables we want to select from the Census API 
race_codes <- as.vector(unlist(race_codes))
```


```{r}
### Get the variables for the ACS census; this is different from the decenniel data
census_var_acs <- load_variables(year = 2010, dataset = 'acs5', cache=T)
# All races except for hispanic or latino
census_race <- census_var_acs[grepl("^RACE$", census_var_acs$concept), ]
### as well as "Total!!", which are the different demographic groups
census_race1 <- census_race[grepl("^Estimate!!Total!!", census_race$label), ]
### Include the "Total" population
census_race1 <- rbind(census_race1, census_race%>%filter(label == "Estimate!!Total")) ###
### Create a variable with the race
census_race1$race <- substring(census_race1$label, 18)
### Only include the races alone, and "Two or more races", and the total
census_race1$race[census_race1$race == ""] <- "TotalAll"
### Remove the more specific "Two or more races" variables
census_race1 <- census_race1 %>%
  filter(!race %in% c("Two or more races!!Two races including Some other race", "Two or more races!!Two races excluding Some other race, and three or more races"))
```

```{r}
#### Find the total hispanic or latino origin
race_hl <- census_var_acs[grepl("^HISPANIC OR LATINO ORIGIN BY RACE", census_var_acs$concept), ]
total_hl <- race_hl[grepl("^Estimate!!Total$", race_hl$label), ]
### Change the label to be "TotalHispanicLatino", to separate from the total population
total_hl$label <- "TotalHispanicLatino"
total_hl$race <- c("Hispanic or Latino")
all_races <- rbind(census_race1, total_hl) ### 
race_codes <- all_races[,1]
### These are the variables we want to select from the Census API 
race_codes <- as.vector(unlist(race_codes))
```



# Functions to extract data



```{r }
pop_func <- function(x,y){
  tryCatch(
    expr = {
       df <- get_decennial(geography = "county", 
                                  variables = c(race_codes), 
                                  year = y, state = x,
                                  geometry = TRUE)
      df <- df %>% group_by(NAME, variable) %>% summarize(population = value)
      if(str_detect(x, "^[:upper:]+$") == FALSE){stop("State abbreviations are two capital letters")} 
      else{return(df)}
      },
    error = {
      if (nchar(x) != 2){"The function only accepts state abbreviations"}
      if(is.character(x) == FALSE){"State abbreviations are two letter strings"}
      if (nchar(y) != 4 | is.numeric(y) == FALSE){"Years must be four digits long"}
      }
    )
}
```



```{r}
### Alternate population function:
population_func <- function(year, state){
  library(sf)
  ### Error checking for the inputs 
  ### Verify year is a numeric
  if (!is.numeric(year)){
    stop("Year must be a numeric value, not a character.")
  }
  ### Verify that the year is between 2005 and 2021
  if (year < 2005 | year > 2021){
    stop("American Community Survey Data is only available between 2005 and 2020.")
  }
  ### Check that state is a character
  if (!is.character(state)){
    stop("State must be a character.")
  }
  ### State must be a two-letter code, all caps
  if (!state %in% state.abb){
    stop("The state must be a two-letter code, with both letters capitalized.")
  }
  
  ### These are the codes for the race variables; see above for how they were extracted from all variables
   race_var <- c("B02001_002",
                 "B02001_003",
                 "B02001_004",
                 "B02001_005",
                 "B02001_006",
                 "B02001_007",
                 "B02001_008",
                 "B02001_001",
                 "B03002_001")
   ### Use the acs survey, not the decenniel survey
   data <- get_acs(geography = "county", 
                variables = c(race_var), 
                year = year, 
                state = state,
                geometry = TRUE)
   ### Create a column with the demographic group
   data$race <- case_when(
     data$variable == "B02001_002" ~ "Total White alone",
     data$variable == "B02001_003" ~ "Total Black or African American alone",
     data$variable == "B02001_004" ~ "Total American Indian and Alaska Native alone",
    data$variable == "B02001_005" ~ "Total Asian alone",
     data$variable == "B02001_006" ~ "Total Native Hawaiian and Other Pacific Islander alone",
     data$variable == "B02001_007" ~ "Total some other race alone",
     data$variable == "B02001_008" ~ "Total two or more races",
     data$variable == "B02001_001" ~ "Total population",
     data$variable == "B03002_001" ~ "Total hispanic latino"
   )
   total_population <- data%>%filter(race == "Total population")
   # print(head(geometry))
   # 
   # # data <- as.data.frame(data)
   # total_population <- data%>%filter(race == "Total population")
   
   data <- st_join(data, total_population)
   # return(data)
   data <- data%>%
      select(c(GEOID.x, GEOID.y, estimate.x, estimate.y, race.x, geometry))%>%
      ### Create a new variable that is the proportion of each race
      mutate(race_prop = estimate.x / estimate.y)
  # 
  # 
  #  colnames(data) <- c("GEOID", "population", "total_population", "race", "race_proportion", "geometry")
  #  
  #  ### Add geometry 
  #  print(head(data))
  #  # data$GEOID <- as.numeric(data$GEOID)
  #  # geometry$GEOID <- as.numeric(geometry$GEOID)
  #  data <- st_join(data, geometry)
  #  
  #  
  # #  total_population <- data%>%
  # # filter(race == "Total population")
  # # 
  # #  data <- left(data, total_population, by = "GEOID")
  # # data <- data%>%
  # #   select(c(countytract, variable.x, population.x, race.x, population.y))%>%
  # # ### Create a new variable that is the proportion of each race
  # # mutate(race_prop = population.x / population.y)
  # #  data$year <- rep(year, nrow(data))
  # #  ### Extract county and state from the NAME variable here
  #  
   return(data)
   
}
```

```{r}
test <- population_func(2009, "MI")
```

```{r}
head(test)
```

```{r}
### Find percentages of each demographic group HERE
test <- as.data.frame(test)
```

```{r}
total_population <- test%>%filter(race == "Total population")
```

```{r}
census_data <- left_join(test, total_population, by = "GEOID")

```

```{r}
census_data <- census_data%>%
  select(c(GEOID, estimate.x, estimate.y, race.x))%>%
  ### Create a new variable that is the proportion of each race
  mutate(race_prop = estimate.x / estimate.y)
```


```{r}
head(census_data, 10)
```



