---
title: "506 Project Functions"
output:
  html_document: default
  pdf_document: default
date: "2022-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r warning = FALSE, message = FALSE}
library(dplyr)
library(tidycensus)
library(tidyverse)
library(stringr)
library(jsonlite)
library(ggplot2) 
library(maps)
library(usmap)
library(RAQSAPI)
```

```{r message = FALSE, echo = TRUE, results = "hide"}
### Comment out these lines of code; this will change depending 
readRenviron("~/.Renviron")
Sys.getenv("CENSUS_API_KEY")
```

# Population Function

```{r}
### Get the variables for the ACS census; this is different from the decenniel data
census_var_acs <- load_variables(year = 2010, dataset = 'acs5', cache=T)
# All races except for hispanic or latino
census_race <- census_var_acs[grepl("^RACE$", census_var_acs$concept), ]
### as well as "Total!!", which are the different demographic groups
census_race1 <- census_race[grepl("^Estimate!!Total!!", census_race$label), ]
### Include the "Total" population
census_race1 <- rbind(census_race1, census_race%>%filter(label == "Estimate!!Total")) ###
### Create a variable with the race
census_race1$race <- substring(census_race1$label, 18)
### Only include the races alone, and "Two or more races", and the total
census_race1$race[census_race1$race == ""] <- "TotalAll"
### Remove the more specific "Two or more races" variables
census_race1 <- census_race1 %>%
  filter(!race %in% c("Two or more races!!Two races including Some other race", "Two or more races!!Two races excluding Some other race, and three or more races"))
#### Find the total hispanic or latino origin
race_hl <- census_var_acs[grepl("^HISPANIC OR LATINO ORIGIN BY RACE", census_var_acs$concept), ]
total_hl <- race_hl[grepl("^Estimate!!Total$", race_hl$label), ]
### Change the label to be "TotalHispanicLatino", to separate from the total population
total_hl$label <- "TotalHispanicLatino"
total_hl$race <- c("Hispanic or Latino")
all_races <- rbind(census_race1, total_hl) ### 
race_codes <- all_races[,1]
### These are the variables we want to select from the Census API 
race_codes <- as.vector(unlist(race_codes))
```
# Population Function

```{r}
### Have the function accept a variable number of years
population_func <- function(year, state){
  ### Error checking for the inputs 
  ### Verify year is a numeric
  if (!is.numeric(year)){
    stop("Year must be a numeric value, not a character.")
  }
  ### Verify that the year is between 2005 and 2021
  if (year < 2005 | year > 2021){
    stop("American Community Survey Data is only available between 2005 and 2020.")
  }
  ### Check that state is a character
  if (!is.character(state)){
    stop("State must be a character.")
  }
  ### State must be a two-letter code, all caps
  if (!state %in% state.abb){
    stop("The state must be a two-letter code, with both letters capitalized.")
  }
  
  ### These are the codes for the race variables; see above for how they were extracted from all variables
   race_var <- c("B02001_002",
                 "B02001_003",
                 "B02001_004",
                 "B02001_005",
                 "B02001_006",
                 "B02001_007",
                 "B02001_008",
                 "B02001_001",
                 "B03002_001")
   ### Use the acs survey, not the decenniel survey
   data <- get_acs(geography = "county", 
                variables = c(race_var), 
                year = year, 
                state = state,
                geometry = TRUE)
   ### Create a column with the demographic group
   data$race <- case_when(
     data$variable == "B02001_002" ~ "Total White alone",
     data$variable == "B02001_003" ~ "Total Black or African American alone",
     data$variable == "B02001_004" ~ "Total American Indian and Alaska Native alone",
    data$variable == "B02001_005" ~ "Total Asian alone",
     data$variable == "B02001_006" ~ "Total Native Hawaiian and Other Pacific Islander alone",
     data$variable == "B02001_007" ~ "Total some other race alone",
     data$variable == "B02001_008" ~ "Total two or more races",
     data$variable == "B02001_001" ~ "Total population",
     data$variable == "B03002_001" ~ "Total hispanic latino"
   )
   geometry <- as.data.frame(data%>%select(c(geometry, GEOID, NAME)))
   #print(head(geometry))
   
   data <- as.data.frame(data)
   total_population <- data%>%filter(race == "Total population")
   data <- left_join(data, total_population, by = "GEOID")
   data <- data %>%
      select(c(GEOID, estimate.x, estimate.y, race.x))%>%
      ### Create a new variable that is the proportion of each race
      mutate(race_prop = estimate.x / estimate.y)
    colnames(data) <- c("GEOID", "population", "total_population", 
                        "race", "race_proportion")
    data <- merge(data, geometry, by = "GEOID", all.x=TRUE)
    total_population <- data %>% filter(race == "Total population")
    data <- left_join(data, total_population, by = "GEOID")
    data <- data %>% 
  # ### Create a new variable that is the proportion of each race
      mutate(race_prop = population.x / population.y)
    data$year <- rep(year, nrow(data)) 
    data <- data[,c("GEOID", "population.x", "total_population.x", "race.x", "race_proportion.x", "NAME.x", "year")] # take out geometry.x
    colnames(data) <- c("GEOID", "population", "total_population", "race", "race_proportion", "NAME", "year")
   return(data)}
```

# EPA Function

```{r}
### Create an account by replacing "myemail@example.com" with your email:
### https://aqs.epa.gov/data/api/signup?email=myemail@example.com
email <- "seegerab@umich.edu"
key <- "greengazelle94"
```


- Inputs: state, pollutant, year
- Output: a data frame with the average concentration of the pollutant for each year for each county in the state 

```{r}
download.dailyEPA <- function(state, year, pollutant = c("ozone","so2","co","no2","pm25.frm","pm25","pm10")){
  if(pollutant=="ozone"){param="44201"}
  if(pollutant=="so2"){param="42401"}
  if(pollutant=="co"){param="42101"}
  if(pollutant=="no2"){param="42602"}
  if(pollutant=="pm25.frm"){param="88101"}
  if(pollutant=="pm25"){param="88502"}
  if(pollutant=="pm10"){param="81102"}
  
URL <- paste0("https://aqs.epa.gov/data/api/dailyData/byState?",
              "email=", email,"&",
              "key=", key ,"&", 
              "param=", param,"&", 
              "bdate=", year,"0101&",
              "edate=", year,"0101&",
              "state=", state)
print(URL)
df <- data.frame(fromJSON(URL))
df <- subset(df, select = c(5:ncol(df)))
colnames(df) <- gsub("Data.", "", colnames(df), fixed=TRUE)
df$year <- format(as.Date(df$date_local, format="%Y-%m-%d"),"%Y")

# Arithmetic Mean (Daily)- The measure of central tendency obtained from the sum of the observed pollutant data values in the daily data set divided by the number of values that comprise the sum for the daily data set. 

new_df <- df %>% 
          group_by(county, year) %>% 
          summarize(mean_aqi = mean(aqi, na.rm = TRUE),
                    mean_conc = mean(arithmetic_mean))

# Creating AQI categories
new_df$aqi_cat <- as.factor(
  ifelse(new_df$mean_aqi >= 0 & new_df$mean_aqi <= 50, "Good",
  ifelse(new_df$mean_aqi >= 51 & new_df$mean_aqi <= 100, "Moderate", 
  ifelse(new_df$mean_aqi >= 101 & new_df$mean_aqi <= 150, "Unhealthy for Sensitive Groups", 
  ifelse(new_df$mean_aqi >= 151 & new_df$mean_aqi <= 200, "Unhealthy", 
  ifelse(new_df$mean_aqi > 201 & new_df$mean_aqi <= 300, "Very Unhealthy", 
  ifelse(new_df$mean_aqi >= 301 & new_df$mean_aqi <= 500, "Hazardous",0)))))))

new_df <- new_df %>% select(county, mean_conc, mean_aqi, aqi_cat, year)%>%
  mutate(pollutant = pollutant)
}
```

```{r message=FALSE}
### Call population function to get data for California in 2012, 2016, and 2020
ca1 <- population_func(2012, "CA")
### Create a county variable that does not include state name. Will be used to merge population data with EPA data
ca1$county <- substr(ca1$NAME,1,nchar(ca1$NAME)-18)

ca2 <- population_func(2016, "CA")
ca2$county <- substr(ca2$NAME,1,nchar(ca2$NAME)-18)


ca3 <- population_func(2020, "CA")
ca3$county <- substr(ca3$NAME,1,nchar(ca3$NAME)-18)

ca <- rbind(ca1,ca2,ca3)
write.csv(ca, "/Users/VickiChang/Desktop/ca.csv")
```

```{r message=FALSE}
### Call population function to get data for Oregon in 2012, 2016, and 2020
or1 <- population_func(2012, "OR")
### Create a county variable that does not include state name. Will be used to merge population data with EPA data
or1$county <- substr(or1$NAME,1,nchar(or1$NAME)-14)

or2 <- population_func(2016, "CA")
or2$county <- substr(or2$NAME,1,nchar(or2$NAME)-14)


or3 <- population_func(2020, "CA")
or3$county <- substr(or3$NAME,1,nchar(or3$NAME)-14)

or <- rbind(or1,or2,or3)
write.csv(or, "/Users/VickiChang/Desktop/or.csv")
```
  
```{r message=FALSE}
### Call population function to get data for Washington in 2012, 2016, and 2020
wa1 <- population_func(2012, "WA")
### Create a county variable that does not include state name. Will be used to merge population data with EPA data
wa1$county <- substr(wa1$NAME,1,nchar(wa1$NAME)-18)

wa2 <- population_func(2016, "WA")
wa2$county <- substr(wa2$NAME,1,nchar(wa2$NAME)-18)

wa3 <- population_func(2020, "WA")
wa3$county <- substr(wa3$NAME,1,nchar(wa3$NAME)-18)

wa <- rbind(wa1,wa2,wa3)
write.csv(wa, "/Users/VickiChang/Desktop/wa.csv")
```

```{r}
ca <- read.csv("/Users/VickiChang/Desktop/506 Data Files/ca.csv")
ca_epa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/ca_epa.csv")
ca <- ca[,-1]
```

```{r}
ca$county <- stringr::str_trim(ca$county)
ca_full <- left_join(ca, ca_epa, by = "county")
ca_full <- ca_full[,c(1:7,9,10)]
colnames(ca_full)[which(colnames(ca_full) == "year.x")] <- "year"
```

```{r}
or <- read.csv("/Users/VickiChang/Desktop/506 Data Files/or.csv")
or_epa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/or_epa.csv")
```

```{r}
or$county <- stringr::str_trim(or$county)
or_full <- left_join(or[,-1], or_epa, by = "county")
or_full <- or_full[,c(1:7,9,10)]
colnames(or_full)[which(colnames(or_full) == "year.x")] <- "year"
```

```{r}
wa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/wa.csv")
wa_epa <- read.csv("/Users/VickiChang/Desktop/506 Data Files/wa_epa.csv")
```

```{r}
wa$county <- stringr::str_trim(wa$county)
wa_full <- left_join(wa[,-1], wa_epa, by = "county")
wa_full <- wa_full[,c(1:7,9,10)]
colnames(wa_full)[which(colnames(wa_full) == "year.x")] <- "year"
```

```{r}
write.csv(ca_full, "/Users/VickiChang/Desktop/ca_full.csv")
write.csv(or_full, "/Users/VickiChang/Desktop/or_full.csv")
write.csv(wa_full, "/Users/VickiChang/Desktop/wa_full.csv")
```


 
